#!/usr/bin/env ruby

require 'braingasm'
require 'braingasm/version'
require 'braingasm/errors'
require 'braingasm/options'
require 'trollop'

def err(message)
  $stderr.puts message
  exit 1
end

opts = Trollop::options do
  version "Braingasm v#{Braingasm::VERSION}"

  opt :zero,          "EOF returns 0 (default)"
  opt :negative,      "EOF returns -1"
  opt :as_is,         "EOF leaves cell unchanged"
  conflicts :zero, :negative, :as_is

  opt :unbound,       "Allow arbitrarily large cells"
  opt :cell_size,     "Cell size in bits",
                      :short => '-s',
                      :default => 8
  conflicts :unbound, :cell_size
end

Braingasm.handle_options(opts)

filename = ARGV.shift
err "Error: No filname given" unless filename
err "Error: No such file: #{filename}" unless File.exists?(filename)

begin
  input = IO.read(filename)
  machine = Braingasm.initialize_machine(input)
  machine.run
rescue Braingasm::BraingasmError => e
  err "#{e.type}: #{e.message}"
end
